version: '3.8'
services:
  frontend:
    container_name: frontend_fall
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend:/app
    ports:
      - "3000:3000"
    stdin_open: true
    tty: true
    networks:
      - project_network_fall

  backend:
    container_name: backend_fall
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend:/app
    ports:
      - "3001:3001"
      - "5555:5555"
    stdin_open: true
    tty: true
    depends_on:
      - db
    networks:
      - project_network_fall

  db:
    container_name: project_postgres
    image: postgres:15
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: dbname
    ports:
      - "5411:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - project_network_fall
volumes:
  db_data:
  frontend-node-modules:
  backend-node-modules:

networks:
  project_network_fall:
    name: project_network_fall
    driver: bridge